### ISSUE TITLE
The new repo on GitLab isn't public

### ISSUE THREAD

**Issue by pcowgill** [BOB-Chicago/dev-series#2]
https://gitlab.com/BOB-Chicago/dev-series

**Comment by GambolingPangolin** [comment]
This is our public repo.

**Comment by pcowgill** [comment]
@GambolingPangolin Ah ok then FYI the link in the latest meetup email was wrong

**Comment by GambolingPangolin** [comment]
Oh oops!  We'll be more careful next time :grin:
